# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'MeatHeat' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MeatHeat
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'Alamofire', '4.8.2'

  target 'MeatHeatTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MeatHeatUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
